
import com.sun.glass.events.KeyEvent;
import java.awt.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MONAEM
 */
public class Login_page extends javax.swing.JFrame {

    /**
     * Creates new form Login_page
     */
    public Login_page() {
        initComponents();
        
        ImageIcon background = new ImageIcon(getClass().getResource("army_log.png"));
        this.setIconImage(background.getImage());
        this.setBounds(10, 10, 1500, 1000);
        getContentPane().setBackground(Color.GRAY);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JLabel();
        admin = new javax.swing.JButton();
        user = new javax.swing.JButton();
        adminpas = new javax.swing.JPasswordField();
        passlab = new javax.swing.JLabel();
        match = new javax.swing.JLabel();
        usertextfil = new javax.swing.JTextField();
        userpasfil = new javax.swing.JPasswordField();
        idlab = new javax.swing.JLabel();
        userpass = new javax.swing.JLabel();
        match1 = new javax.swing.JLabel();
        crebut = new javax.swing.JButton();
        forpas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(10, 10, 1500, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setBackground(new java.awt.Color(102, 255, 102));
        Login.setFont(new java.awt.Font("Microsoft Yi Baiti", 3, 36)); // NOI18N
        Login.setForeground(new java.awt.Color(51, 51, 255));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("LOGIN");
        Login.setOpaque(true);
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1288, 149));

        admin.setBackground(new java.awt.Color(153, 153, 153));
        admin.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        admin.setForeground(new java.awt.Color(51, 0, 51));
        admin.setText("Admin");
        admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        getContentPane().add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 216, 203, 73));

        user.setBackground(new java.awt.Color(153, 153, 153));
        user.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        user.setForeground(new java.awt.Color(51, 0, 51));
        user.setText("User");
        user.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 412, 203, 72));

        adminpas.setBackground(new java.awt.Color(0, 153, 0));
        adminpas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        adminpas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        adminpas.setCaretColor(new java.awt.Color(0, 255, 204));
        adminpas.setVisible(false);
        adminpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminpasActionPerformed(evt);
            }
        });
        adminpas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adminpasKeyReleased(evt);
            }
        });
        getContentPane().add(adminpas, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 235, 203, -1));

        passlab.setBackground(new java.awt.Color(0, 0, 0));
        passlab.setText("Password");
        passlab.setVisible(false);
        getContentPane().add(passlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 244, 69, 24));

        match.setForeground(new java.awt.Color(204, 0, 0));
        match.setText("* Password Do Not Match");
        match.setVisible(false);
        getContentPane().add(match, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 295, 145, 27));

        usertextfil.setBackground(new java.awt.Color(153, 153, 0));
        usertextfil.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        usertextfil.setVisible(false);
        getContentPane().add(usertextfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 440, 231, 44));

        userpasfil.setBackground(new java.awt.Color(204, 204, 0));
        userpasfil.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        userpasfil.setVisible(false);
        userpasfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userpasfilKeyReleased(evt);
            }
        });
        getContentPane().add(userpasfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 440, 239, 44));

        idlab.setText("ID");
        idlab.setVisible(false);
        getContentPane().add(idlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 419, 77, -1));

        userpass.setText("Password");
        userpass.setVisible(false);
        getContentPane().add(userpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 419, 85, -1));

        match1.setForeground(new java.awt.Color(204, 0, 0));
        match1.setText("* Password Do Not Match");
        match1.setVisible(false);
        getContentPane().add(match1, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 490, 145, 27));

        crebut.setBackground(new java.awt.Color(51, 255, 0));
        crebut.setForeground(new java.awt.Color(0, 51, 204));
        crebut.setText("Create Password");
        crebut.setVisible(false);
        crebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crebutActionPerformed(evt);
            }
        });
        getContentPane().add(crebut, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 543, 215, -1));

        forpas.setBackground(new java.awt.Color(102, 255, 0));
        forpas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        forpas.setForeground(new java.awt.Color(0, 0, 0));
        forpas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forpas.setText("Forget Pasword??");
        forpas.setVisible(false);
        forpas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        forpas.setOpaque(true);
        forpas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                forpasPropertyChange(evt);
            }
        });
        getContentPane().add(forpas, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 543, 231, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        passlab.setVisible(true);
        adminpas.setVisible(true);
    }//GEN-LAST:event_adminActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
       idlab.setVisible(true);
       userpass.setVisible(true);
       usertextfil.setVisible(true);
       userpasfil.setVisible(true);
       crebut.setVisible(true);
       forpas.setVisible(true);
    }//GEN-LAST:event_userActionPerformed

    private void adminpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpasActionPerformed
        if(adminpas.getText().equals("asdf1234")){
            Admin_page op = new Admin_page();
            op.setVisible(true);
            op.setBounds(10, 10, 1500, 1000);
            
            this.setVisible(false);
        }else{
            match.setVisible(true);
        }
    }//GEN-LAST:event_adminpasActionPerformed

    private void adminpasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminpasKeyReleased
        if(evt.getKeyChar() == KeyEvent.VK_BACKSPACE || evt.getKeyChar() == KeyEvent.VK_DELETE){
            match.setVisible(false);
        }
    }//GEN-LAST:event_adminpasKeyReleased

    private void userpasfilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userpasfilKeyReleased
       if(evt.getKeyChar() == KeyEvent.VK_BACKSPACE || evt.getKeyChar() == KeyEvent.VK_DELETE){
            match.setVisible(false);
        }
    }//GEN-LAST:event_userpasfilKeyReleased

    private void crebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crebutActionPerformed

    private void forpasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_forpasPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_forpasPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login;
    private javax.swing.JButton admin;
    private javax.swing.JPasswordField adminpas;
    private javax.swing.JButton crebut;
    private javax.swing.JLabel forpas;
    private javax.swing.JLabel idlab;
    private javax.swing.JLabel match;
    private javax.swing.JLabel match1;
    private javax.swing.JLabel passlab;
    private javax.swing.JButton user;
    private javax.swing.JPasswordField userpasfil;
    private javax.swing.JLabel userpass;
    private javax.swing.JTextField usertextfil;
    // End of variables declaration//GEN-END:variables
}
