
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author MONAEM
 */
public class Adminser extends javax.swing.JFrame {

    String path, path1;
    private ImageIcon Snk_Image;

    public Adminser() {
        initComponents();
        ImageIcon background = new ImageIcon(getClass().getResource("army_log.png"));
        this.setIconImage(background.getImage());
        getContentPane().setBackground(new Color(204, 204, 255));
        getContentPane().setLayout(null);
        id.setText("SNK-");
        snk_img.setIcon(new ImageIcon(getClass().getResource("se_img.png")));

        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        snk_img = new javax.swing.JLabel();
        browse = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        father = new javax.swing.JTextField();
        mother = new javax.swing.JTextField();
        core = new javax.swing.JComboBox<>();
        rank = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        dob = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        nation = new javax.swing.JTextField();
        blood = new javax.swing.JComboBox<>();
        hom = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        unit = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        phn = new javax.swing.JTextField();
        region = new javax.swing.JTextField();
        joinda = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("High Tower Text", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("'''''Search Data'''''");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 12, 1204, 63);
        getContentPane().add(snk_img);
        snk_img.setBounds(45, 106, 250, 250);

        browse.setBackground(new java.awt.Color(255, 255, 255));
        browse.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        browse.setForeground(new java.awt.Color(51, 51, 51));
        browse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Brows.jpg"))); // NOI18N
        browse.setText("Browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });
        getContentPane().add(browse);
        browse.setBounds(30, 370, 266, 80);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(411, 157, 167, 41);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Father:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(411, 204, 167, 41);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Mother:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(411, 251, 167, 41);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Core:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(411, 298, 167, 41);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Rank:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(411, 347, 167, 41);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Gender:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(411, 394, 167, 41);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Birthday:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(411, 441, 167, 41);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Email:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(411, 488, 167, 41);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("National:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(411, 535, 167, 41);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Blood Grup:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(411, 582, 167, 41);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Home:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(411, 629, 167, 41);
        getContentPane().add(name);
        name.setBounds(621, 159, 452, 41);
        getContentPane().add(father);
        father.setBounds(621, 206, 452, 41);
        getContentPane().add(mother);
        mother.setBounds(621, 253, 452, 41);

        core.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EME", "ARTILARY" }));
        getContentPane().add(core);
        core.setBounds(621, 300, 452, 41);

        rank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", " Lieutenant general", " Major general", " Brigadier general", "Colonel", "Lieutenant colonel", " Major", "Captain", "Lieutenant", " Second lieutenant" }));
        getContentPane().add(rank);
        rank.setBounds(621, 347, 452, 41);

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(gender);
        gender.setBounds(621, 394, 452, 41);

        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        getContentPane().add(dob);
        dob.setBounds(621, 441, 452, 41);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(621, 488, 452, 41);
        getContentPane().add(nation);
        nation.setBounds(621, 537, 452, 41);

        blood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        getContentPane().add(blood);
        blood.setBounds(621, 582, 452, 41);

        hom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chittagong", "Rangamati", "Bandarban", "Khagrachori" }));
        getContentPane().add(hom);
        hom.setBounds(621, 629, 452, 41);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText("Enter ID ::");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(411, 106, 167, 42);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        getContentPane().add(id);
        id.setBounds(621, 109, 452, 42);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("Unit");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(411, 676, 167, 40);

        unit.setEditable(false);
        getContentPane().add(unit);
        unit.setBounds(621, 676, 452, 40);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("Phone Num:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(411, 722, 167, 41);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText("Region:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(411, 771, 167, 40);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel18.setText("Join Date:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(411, 820, 167, 41);

        phn.setEditable(false);
        getContentPane().add(phn);
        phn.setBounds(621, 724, 452, 41);

        region.setEditable(false);
        getContentPane().add(region);
        region.setBounds(621, 773, 452, 41);

        joinda.setEditable(false);
        joinda.setFont(new java.awt.Font("Dialog", 1, 18));
        joinda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joindaActionPerformed(evt);
            }
        });
        getContentPane().add(joinda);
        joinda.setBounds(621, 822, 452, 42);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("Address :");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(411, 870, 167, 41);

        address.setColumns(20);
        address.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        address.setRows(5);
        address.setLineWrap(true);
        address.setEditable(false);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(621, 870, 452, 100);

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        update.setForeground(new java.awt.Color(153, 0, 0));
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.gif"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(30, 570, 266, 87);

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(153, 0, 0));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.gif"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(30, 670, 266, 87);

        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Exit.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(40, 900, 70, 60);

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(153, 0, 0));
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(30, 770, 266, 100);

        print.setBackground(new java.awt.Color(255, 255, 255));
        print.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        print.setForeground(new java.awt.Color(153, 0, 0));
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(30, 470, 266, 87);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void joindaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joindaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joindaActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sainik_data", "root", "");

            String info = "SELECT * FROM `info` WHERE `id` ='" + id.getText() + "'";

            PreparedStatement info1 = conn.prepareStatement(info);

            ResultSet rs = info1.executeQuery();

            while (rs.next()) {
                name.setText(rs.getString("name"));
                father.setText(rs.getString("father"));
                mother.setText(rs.getString("mother"));
                core.setSelectedItem(rs.getString("core"));
                rank.setSelectedItem(rs.getString("rank"));
                gender.setSelectedItem(rs.getString("gender"));
                dob.setText(rs.getString("dob"));
                email.setText(rs.getString("email"));
                nation.setText(rs.getString("national"));
                blood.setSelectedItem(rs.getString("blood"));
                hom.setSelectedItem(rs.getString("home"));
                unit.setText(rs.getString("unit"));
                phn.setText(rs.getString("phn"));
                region.setText(rs.getString("region"));
                joinda.setText(rs.getString("join"));
                address.setText(rs.getString("address"));

                snk_img.setIcon(ResizeImage(rs.getString("img")));

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_idActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filt = new FileNameExtensionFilter("*.images", "*.jpg", "*.png", "*.gif");
        file.addChoosableFileFilter(filt);
        int result = file.showSaveDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            path = selectedFile.getAbsolutePath();
            snk_img.setIcon(ResizeImage(path));
        } else {
            JOptionPane.showMessageDialog(null, "No File Selected");
        }
    }//GEN-LAST:event_browseActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sainik_data", "root", "");

            String query = "UPDATE `info` SET `img`=?,`name`=?,`father`=?,`mother`=?,`home`=?,`gender`=?,`email`=?,"
                    + "`national`=?,`dob`=?,`blood`=?,`core`=?,`rank`=? WHERE`id` ='" + id.getText() + "'";
            PreparedStatement pp = conn.prepareStatement(query);

            pp.setString(1, path);
            pp.setString(2, name.getText());
            pp.setString(3, father.getText());
            pp.setString(4, mother.getText());
            pp.setString(5, hom.getSelectedItem().toString());
            pp.setString(6, gender.getSelectedItem().toString());
            pp.setString(7, email.getText());
            pp.setString(8, nation.getText());
            pp.setString(9, dob.getText());
            pp.setString(10, blood.getSelectedItem().toString());
            pp.setString(11, core.getSelectedItem().toString());
            pp.setString(12, rank.getSelectedItem().toString());

            pp.executeUpdate();

            JOptionPane.showMessageDialog(null, "Successfully Updated");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sainik_data", "root", "");

            String del = "DELETE FROM `info` WHERE `id` ='" + id.getText() + "'";
            PreparedStatement pp = conn.prepareStatement(del);
            pp.execute();

            JOptionPane.showMessageDialog(null, "Successfully Deleted");
            clr();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clr();
    }//GEN-LAST:event_clearActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Admin_page op = new Admin_page();
        op.setVisible(true);
        op.setBounds(300, 50, 960, 700);

        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        if (evt.getKeyChar() == KeyEvent.VK_BACKSPACE || evt.getKeyChar() == KeyEvent.VK_DELETE) {
            clr();
        }
    }//GEN-LAST:event_idKeyReleased

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed

        JFileChooser jf = new JFileChooser();
        jf.setCurrentDirectory(new File("user.home"));
        jf.setSelectedFile(new File("Info" + ".pdf"));

        int re = jf.showSaveDialog(null);
        if (re == JFileChooser.APPROVE_OPTION) {
            String path = jf.getSelectedFile().getAbsolutePath();
            try {
                Document document = new Document();

                PdfWriter.getInstance(document, new FileOutputStream(path));

                document.open();

                String s1
                        = "===========Army Person Information============\n"
                        + "           ID :: " + id.getText() + "\n"
                        + "         Name :: " + rank.getSelectedItem() + " " + name.getText() + "\n"
                        + "  Father Name :: " + father.getText() + "\n"
                        + "  Mother Name :: " + mother.getText() + "\n"
                        + "Bate Of Birth :: " + dob.getText() + "\n"
                        + "        Gender:: " + gender.getSelectedItem() + "\n"
                        + "  Blood Group :: " + blood.getSelectedItem() + "\n"
                        + "Home District :: " + hom.getSelectedItem() + "\n"
                        + " National ID  :: " + nation.getText() + "\n"
                        + "        Email :: " + email.getText() + "\n"
                        + "       Adress :: " + address.getText() + "\n"
                        + "         Core :: " + core.getSelectedItem() + "\n"
                        + "       Region :: " + region.getText() + "\n"
                        + "         Unit :: " + unit.getText() + "\n"
                        + "     Join Date:: " + joinda.getText() + "\n";
                Paragraph chunk = new Paragraph(s1, FontFactory.getFont(FontFactory.TIMES, 20, java.awt.Font.PLAIN));
                document.add(chunk);
                document.close();

                JOptionPane.showMessageDialog(null, "File Save Successfull");
            } catch (FileNotFoundException | DocumentException ex) {
                System.out.println(ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "File Save Unsuccessfull !!!");
        }

    }//GEN-LAST:event_printActionPerformed
    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(snk_img.getWidth(), snk_img.getHeight(), Image.SCALE_SMOOTH);
        Snk_Image = new ImageIcon(newImg);
        return Snk_Image;
    }

    public void clr() {
        id.setText("SNK-");
        name.setText("");
        father.setText("");
        mother.setText("");
        core.setSelectedIndex(0);
        rank.setSelectedIndex(0);
        gender.setSelectedIndex(0);
        dob.setText("");
        email.setText("");
        nation.setText("");
        blood.setSelectedIndex(0);
        hom.setSelectedIndex(0);
        unit.setText("");
        phn.setText("");
        region.setText("");
        joinda.setText("");
        address.setText("");

        snk_img.setIcon(new ImageIcon(getClass().getResource("se_img.png")));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JComboBox<String> blood;
    private javax.swing.JButton browse;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> core;
    private javax.swing.JButton delete;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField father;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JComboBox<String> hom;
    public javax.swing.JTextField id;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField joinda;
    private javax.swing.JTextField mother;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nation;
    private javax.swing.JTextField phn;
    private javax.swing.JButton print;
    private javax.swing.JComboBox<String> rank;
    private javax.swing.JTextField region;
    private javax.swing.JLabel snk_img;
    private javax.swing.JTextField unit;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
