
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author MONAEM
 */
public class admin_apli extends javax.swing.JFrame {

    private String time, time1;
    String ap;

    /**
     * Creates new form admin_apli
     */
    public admin_apli() {
        initComponents();
        ImageIcon background = new ImageIcon(getClass().getResource("army_log.png"));
        this.setIconImage(background.getImage());
        this.setResizable(false);
        getContentPane().setBackground(new Color(255, 204, 204));

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        time = sdf.format(date);

        SimpleDateFormat sdf1 = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
        Date date1 = new Date();
        time1 = sdf1.format(date);

        show_user();

        this.setResizable(false);
    }

    public ArrayList<ad_apli> UserList() {
        ArrayList<ad_apli> userList = new ArrayList<>();

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sainik_data", "root", "");
            String qur = "SELECT * FROM `approve` WHERE `date` = '" + time + "'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(qur);
            ad_apli user;
            while (rs.next()) {
                user = new ad_apli(rs.getString("application"), rs.getString("id"), rs.getString("Name"), rs.getString("from"), rs.getString("reason"), rs.getString("to"), rs.getString("date"), rs.getString("dis"), rs.getString("rank"), rs.getString("unit"));
                userList.add(user);
            }

        } catch (SQLException ae) {
            System.out.println(ae);
        }
        return userList;
    }

    public void show_user() {
        ArrayList<ad_apli> List = UserList();
        DefaultTableModel tt = (DefaultTableModel) jTable1.getModel();
        tt.setRowCount(0);
        Object[] Row = new Object[10];
        for (int i = (List.size() - 1); i >= 0; i--) {
            Row[0] = List.get(i).getid();
            Row[1] = List.get(i).getname();
            Row[2] = List.get(i).getrank();
            Row[3] = List.get(i).getunit();
            Row[4] = List.get(i).getfr();
            Row[5] = List.get(i).gettto();
            Row[6] = List.get(i).getreason();
            Row[7] = List.get(i).getdis();
            Row[8] = List.get(i).getdate();
            Row[9] = List.get(i).getappli();
            tt.addRow(Row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ff = new javax.swing.JTextField();
        tt = new javax.swing.JTextField();
        dis = new javax.swing.JComboBox<>();
        send = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 56)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Leave Application");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 1582, 89));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Rank", "Unit", "From", "To", "Reason", "Dission", "Current Date", "Application id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(500);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 107, 1582, 265));

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("From :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 387, 193, 46));

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("To :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 473, 193, 46));

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Approve :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 530, 193, 51));

        ff.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        ff.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(ff, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 387, 341, 51));

        tt.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        tt.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(tt, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 473, 341, 51));

        dis.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        dis.setForeground(new java.awt.Color(255, 255, 255));
        dis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        getContentPane().add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 532, 115, 51));

        send.setBackground(new java.awt.Color(0, 255, 0));
        send.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        send.setForeground(new java.awt.Color(153, 0, 153));
        send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Message-icon.png"))); // NOI18N
        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        getContentPane().add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 618, 179, 48));

        jButton2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Exit.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 688, 104, 48));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Reason ::");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 390, 120, 30));

        rea.setColumns(20);
        rea.setLineWrap(true);
        rea.setWrapStyleWord(true);
        rea.setEditable(false);
        rea.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rea.setRows(5);
        jScrollPane2.setViewportView(rea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 430, 250, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sainik_data", "root", "");

            String up = "UPDATE `approve` SET `from`=?,`to`=?,`dis`=?,`issu date`=? WHERE  `application`=" + ap + "";
            PreparedStatement pp = conn.prepareStatement(up);
            pp.setString(1, ff.getText());
            pp.setString(2, tt.getText());
            pp.setString(3, dis.getSelectedItem().toString());
            pp.setString(4, time1);
            pp.executeUpdate();

            JOptionPane.showMessageDialog(null, "Request Seen Succesfully");
            show_user();
            ff.setText("");
            tt.setText("");
            dis.setSelectedIndex(0);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_sendActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel mod = jTable1.getModel();
        rea.setText(mod.getValueAt(i, 6).toString());
        ap = mod.getValueAt(i, 9).toString();
        ff.setText(mod.getValueAt(i, 4).toString());
        tt.setText(mod.getValueAt(i, 5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Admin_page op = new Admin_page();
        op.setVisible(true);
        op.setBounds(300, 50, 960, 700);

        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_apli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_apli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_apli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_apli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_apli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dis;
    private javax.swing.JTextField ff;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea rea;
    private javax.swing.JButton send;
    private javax.swing.JTextField tt;
    // End of variables declaration//GEN-END:variables
}
